version: "3.7"
services:
  userauth:
    build: userAuth/
    ports:
    - '8000:8000'
    env_file:
    - userAuth/.env
  comicdetails:
    build: comicDetails/
    ports:
    - '8001:8001'
    env_file:
    - comicDetails/.env
  layaway:
    build: layaway/
    ports:
    - '8002:8002'
    env_file:
    - layaway/.env
